language: python
services:
  - redis-server
  - mongodb
  - rabbitmq
before_install:
  - sudo apt-get -q update
  - sudo apt-get install -qq python-scipy
install:
  - ln -s /usr/lib/python``$TRAVIS_PYTHON_VERSION``/dist-packages/scipy ~/virtualenv/python``$TRAVIS_PYTHON_VERSION``_with_system_site_packages/lib/python``$TRAVIS_PYTHON_VERSION``/site-packages/
  - pip install -q $DJANGO
  - pip install -r requirements.txt --use-mirrors
  - pip install -r test-requirements.txt --use-mirrors
before_script:
  - export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
script: python recommends/tests/runtests.py
after_failure:
  - env
  - ls $PYTHONPATH
